apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{- if .Values.image.imagePullSecrets.enabled }}
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecrets.name }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.probe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probe.path }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.path }}
              port: http
          {{- end }}
          {{- if or (eq .Values.configmap.enabled true) (eq .Values.persistence.enabled true) }}
          volumeMounts:
          {{- if .Values.configmap.enabled }}
            - name: config-volume
              mountPath: {{ .Values.configmap.path }}
              subPath: properties
          {{- end }}
          {{- if .Values.persistence.enabled }}
            - name: data-dir
              mountPath: {{ .Values.persistence.path }}
          {{- end }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      {{- if or (eq .Values.configmap.enabled true) (eq .Values.persistence.enabled true) }}
      volumes:
        {{- if .Values.configmap.enabled }}
        - name: config-volume
          configMap:
            name: {{ template "app.fullname" . }}-configmap
        {{- end }}
        {{- if $.Values.persistence.enabled }}
        - name: data-dir
          persistentVolumeClaim:
            claimName: {{ template "app.fullname" $ }}
        {{- end }}
      {{- end }}

      